let hello = document.querySelector('button')
hello.addEventListener('click')
let hello = document.querySelector('button')
hello.addEventListener('click')let hello = document.querySelector('button')
hello.addEventListener('click')let hello = document.querySelector('button')
hello.addEventListener('click')let hello = document.querySelector('button')
hello.addEventListener('click')
let hello = document.querySelector('button')
hello.addEventListener('click')
hello.addEventListener('click')
hello.addEventListener('click')
hello.addEventListener('click')
hello.addEventListener('click')
hello.addEventListener('click')
hello.addEventListener('click')
hello.addEventListener('click')
hello.addEventListener('click')
hello.addEventListener('click')
hello.addEventListener('click')
hello.addEventListener('click')
hello.addEventListener('click')
